import Joi from "joi"

export const UserCreationSchema = Joi.object({
    employee_name: Joi.string().required().example('Anugrah Bhatt'),
    employee_generated_id : Joi.string().required().example('GV-123'),
    profile_image: Joi.string().optional(),
    date_of_joining: Joi.date(),
    probation_period: Joi.string(),
    probation_due_date: Joi.date(),
    work_location: Joi.string(),
    level: Joi.string(),
    grade: Joi.string(),
    cost_center: Joi.string(),
    employee_official_email: Joi.string().required(),
    employee_personal_email: Joi.string(),
    dob_adhaar: Joi.string().required(),
    dob_celebrated: Joi.string(),
    employee_gender_id: Joi.number().required(),
    employee_password: Joi.string().required(),
    role_id: Joi.number().required(),
    master_policy_id: Joi.number().required().example(1),
    units: Joi.array().items(Joi.number()).optional(),
    phone: Joi.string().required(),
    reporting_managers: Joi.array().items(Joi.number().optional()),
    alternate_contact: Joi.string().optional(),
    alternate_email: Joi.string().email().optional()
})

export const UserUpdationSchema = Joi.object({
    employee_name: Joi.string().optional().empty(''),
    employee_generated_id : Joi.string().strict().trim().optional().empty('').example('GV-123'),
    profile_image: Joi.string().optional(),
    date_of_joining: Joi.date().optional(),
    probation_period: Joi.string().optional(),
    probation_due_date: Joi.date().optional(),
    designation: Joi.number().optional(),
    department: Joi.number().optional(),
    work_location: Joi.string().optional(),
    employee_personal_email: Joi.string().optional(),
    dob_adhaar: Joi.string().optional(),
    dob_celebrated: Joi.string().optional(),
    employee_gender_id: Joi.number().optional(),
    master_policy_id: Joi.number().optional().empty('').optional(),
    role_id: Joi.number().optional().empty('').optional(),
    blood_group: Joi.string().optional(),
    employee_official_email: Joi.string().optional(),
    units: Joi.array().items(Joi.number()).optional(),
    phone: Joi.string().optional(),
    religion: Joi.string().optional(),
    nationality: Joi.string().optional(),
    reporting_managers: Joi.array().items(Joi.number().optional()),
    bank_name: Joi.string().optional(),
    bank_branch: Joi.string().optional(),
    account_number: Joi.string().optional(),
    ifsc_code: Joi.string().optional(),
    payroll_details: Joi.string().optional(),
    account_holder_name: Joi.string().optional(),
    pan_number: Joi.string().optional(),
    adhaar_number: Joi.string().optional(),
    profile_image_id: Joi.number().optional(),
    alternate_contact: Joi.string().optional(),
    alternate_email: Joi.string().email().optional(),
});

export const ProfileUpdationSchema = Joi.object({
    employee_name: Joi.string().optional().empty(''),
    profile_image: Joi.string().optional(),
    employee_personal_email: Joi.string().optional(),
    dob_adhaar: Joi.string().optional(),
    dob_celebrated: Joi.string().optional(),
    employee_gender_id: Joi.number().optional(),
    role_id: Joi.number().optional().empty('').optional(),
    blood_group: Joi.string().optional().allow(null),
    employee_official_email: Joi.string().optional(),
    units: Joi.array().items(Joi.number()).optional(),
    phone: Joi.string().optional(),
    religion: Joi.string().optional().allow(null),
    nationality: Joi.string().optional().allow(null),
    reporting_managers: Joi.array().items(Joi.number().optional()),
    bank_name: Joi.string().optional(),
    bank_branch: Joi.string().optional(),
    account_number: Joi.string().optional(),
    ifsc_code: Joi.string().optional(),
    payroll_details: Joi.string().optional(),
    account_holder_name: Joi.string().optional(),
    pan_number: Joi.string().optional(),
    adhaar_number: Joi.string().optional(),
    profile_image_id: Joi.number().optional(),
    alternate_contact: Joi.string().optional().allow(null),
    alternate_email: Joi.string().email().optional().allow(null),
    section: Joi.string().required()
})

export interface User{
    employee_name: string,
    employee_generated_id : string,
    profile_image: string,
    date_of_joining: string,
    probation_period: string,
    probation_due_date: string,
    designation: number,
    department: number,
    work_location: string,
    level: string,
    grade: string,
    cost_center: string,
    employee_official_email: string,
    employee_personal_email: string,
    dob_adhaar: string,
    dob_celebrated: string,
    employee_gender_id: number,
    role_id: number,
    master_policy_id: number,
}